### ISSUE TITLE
Include DNS for server address??

### ISSUE THREAD

**Issue by HanlamSnot** [rrennoir/PyAccEngineer#15]
Is it possible to include DNS address or the standard ip address? Most don't have static IP's so you stand the chance to lose connection during a race. Not the end of the world, but a nice to have.

Thanks for this software though.

**Comment by rrennoir** [comment]
What do you mean by "the standard ip address" ?
For DNS yeah should be easy to add, even though I'm not sure if losing a dynamic ip mid race is possible, they usually change on router reboot 😅

**Comment by HanlamSnot** [comment]
Just the ipv4 address, that you type in to connect to a host.

No I guess not really possibly, but in South Africa we have regular power cuts, where all the infrastructure goes down in a certain area. There isn't much backup systems because they are mostly stolen to sell for money.

So for example, I might be hosting and then lose my connection because of a power cut. Coming online I most probably wont get the same IP as all the infrastructure comes back then it's a balls up mid race.

Look, I agree it's an unlikely scenario, but one none the less at least of concern to me.
