### ISSUE TITLE
Can not connect 

### ISSUE THREAD

**Issue by AndreasWes** [rrennoir/PyAccEngineer#16]
How do I connect with friends? 
If I Click on "As Server" in the main.py programm it will automaticly use my local adress. 
When the second party tried to connect to me he gets the following message 
"creating a clientInstance connecting to 80.135.155.227 TCP Port52596* waiting for connection confirmation."
*we tired the standard one and the TCP Port shown when I Start the server (5 digit)
but I can not confirm him.

When I try to open a headless server this error occures:
__________________________________________________________
C:\Users\andre\Documents\Assetto Corsa Competizione\PyAccEngineer_1_5_7>python headless_server.py
Unhandled error in Deferred:

Traceback (most recent call last):
  File "C:\...\headless_server.py", line 66, in <module>
    headless(sys.argv)
  File "C:\...\headless_server.py", line 55, in headless
    ServerInstance(tcp_port, udp_port)
  File "C:\...\Server.py", line 256, in __init__
    self.tcp_endpoint.listen(TCP_Factory(self.data_queue))
  File "C:\...\Python39\site-packages\twisted\internet\endpoints.py", line 511, in listen
    return defer.execute(
--- <exception caught here> ---
  File "C:\...\Python39\site-packages\twisted\internet\defer.py", line 164, in execute
    result = callable(*args, **kwargs)
  File "C:\...\Python39\site-packages\twisted\internet\posixbase.py", line 568, in listenTCP
    p.startListening()
  File "C:\...\Python39\site-packages\twisted\internet\tcp.py", line 1335, in startListening
    raise CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on any:4269: [WinError 10048] Normalerweise darf jede Socketadresse (Protokoll, Netzwerkadresse oder Anschluss) nur jeweils einmal verwendet werden.

12:13:39.202 | root | Running as headless server with port TCP:4269 UDP:4270
____________________________________________________

what are we doing wrong?

**Comment by rrennoir** [comment]
did you open the port on the router ?

**Comment by rrennoir** [comment]
Idk why I never get notification for issue sry for being 15 days late 😅 
Second error is normal if you already have a server open

First sound like a port forwarding issue on the router

**Comment by AndreasWes** [comment]
_did you open the port on the router ?_

No, I wasn`t sure about this. 
Which port should I open?
"Port52596" which was shown in the error or just the standardports which are selected in the Connection Page? 
I never needed to open ports in the router before. Some other drivers had simmilar problems. 
I guess adding some words to the readme would be helpfull here ;) 
I will test it this week and give you a feedback)

**Comment by rrennoir** [comment]
yeah server owner open port 4269 in TCP and 4270 in UDP
or 4269 on both protocol
